-- 대량의 테스트 데이터 생성
-- 사용자 10만명 생성
INSERT INTO community_user (name, follower_count, following_count, reg_dt, upd_dt)
SELECT 
  CONCAT('User', n),
  FLOOR(RAND() * 1000),
  FLOOR(RAND() * 500),
  NOW(),
  NOW()
FROM 
  (SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 N FROM
   (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
   (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
   (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
   (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
  ) numbers
WHERE n <= 100000;

-- 사용자 인증 정보 생성
INSERT INTO community_user_auth (email, password, role, user_id)
SELECT 
  CONCAT('user', id, '@example.com'),
  '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', -- 'password'
  'USER',
  id
FROM community_user;
