# P6Spy ??
# ?? ??
driverlist=com.mysql.cj.jdbc.Driver
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

# ?? ?? ?? ??
dateformat=yyyy-MM-dd HH:mm:ss
databaseDialectDateFormat=yyyy-MM-dd HH:mm:ss
timestampformat=yyyy-MM-dd HH:mm:ss.SSS
logfile=spy.log

# SQL ???
# ???? ??
multiline=true

# ?? ?? ??? ??
excludecategories=info,debug,result,resultset,batch

# ???? ??? (ms)
executionThreshold=0

# ?????? ??
stacktraceclass=
stacktrace=false
autoflush=true